only run when directories have changed.

diff --git a/.github/workflows/first_cd.yml b/.github/workflows/first_cd.yml
--- a/.github/workflows/first_cd.yml
+++ b/.github/workflows/first_cd.yml
@@ -26,6 +26,22 @@ jobs:
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - run: echo 'The Apply workflow failed.'
+  check_changes:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Check for changes in specific directories
+        id: check_changes
+        run: |
+          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^\.github/|^firstpath/'; then
+            echo "Changes detected in the specified directories."
+          else
+            echo "No changes detected in the specified directories. Exiting early."
+            exit 78  # Use a non-zero exit code to indicate a successful early exit
+          fi
   set_environment:
     needs: success
     runs-on: ubuntu-latest
